export { default as InstanceHeader } from "./InstanceHeader";
export { default as InstanceActions } from "./InstanceActions";
export { default as InstanceTabs } from "./InstanceTabs";
export { default as OverviewTab } from "./OverviewTab";
export { default as TasksTab } from "./TasksTab";
export { default as TimelineTab } from "./TimelineTab";
export { default as DataTab } from "./DataTab";
export { default as StatusBadge } from "./StatusBadge";
export { default as ApprovalBadge } from "./ApprovalBadge";
export { PriorityBadge } from "./PriorityBadge";
